### ISSUE TITLE
Data Tests (missing_values)

### ISSUE THREAD

**Issue by ATLJoeReed** [openelections/openelections-data-tests#15]
Greetings - I'm merging some 2021 race results for the state of Georgia, and I see the data test for missing values is failing. I looked at a few of the results, and sometimes we don't have county and/or precinct data (see example below).

https://sos.ga.gov/elections/election_results/2000_0215/

Also, the check is running against years (2013 - 2017) that haven't been validated yet.

So I have two questions:

1) For missing values in the county and precinct, should we use "Not Available" or something similar?
2) Can we have the test only run on specific years? Maybe use a config file?

Once we get one of the above years validated we could turn the check on for that year. This would make the process more manageable as currently, we are getting 27K lines of log data that is difficult to dig through. Let me know if you need any additional information. Thanks

**Comment by warwickmm** [comment]
Hi @ATLJoeReed, I'll take the blame for any issues with the tests.  The tests are still in their early stages, and can use some improvement.

Regarding your second question:

> 2. Can we have the test only run on specific years? Maybe use a config file?

The intent was to raise potential issues as early as possible, as sometimes there are systematic errors due to bugs in parsing scripts, etc.  But I see your point about the amount of noise.  I can look into [grouping](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#grouping-log-lines) the failure messages by years to clean up the output:

![image](https://user-images.githubusercontent.com/17345532/137637696-2434500a-eb75-4659-896d-4963fd228dff.png)

Would that help make navigating the failures more manageable?  My preference is to run the tests on as many files as possible, regardless of their status.

**Comment by ATLJoeReed** [comment]
@warwickmm - yes, grouping looks good. Would they be grouped by the year? If so that would be perfect. Thanks

**Comment by warwickmm** [comment]
While this issue is also applicable here, I'm going to transfer this to the [openelections-data-tests](https://github.com/openelections/openelections-data-tests) repository since it specifically mentions the missing values test.
